// <auto-generated />
using System;
using EventsTicketingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsTicketingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("EventsTicketingSystem.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Live Coding Lounge – Friday Night",
                            StartsAt = new DateTime(2026, 1, 17, 19, 0, 0, 0, DateTimeKind.Utc),
                            TotalSeats = 50
                        });
                });

            modelBuilder.Entity("EventsTicketingSystem.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HolderName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 6,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 7,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 8,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 9,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 10,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 11,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 12,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 13,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 14,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 15,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 16,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 17,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 18,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 19,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 20,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 21,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 22,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 23,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 24,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 25,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 26,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 27,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 28,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 29,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 30,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 31,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 32,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 33,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 34,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 35,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 36,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 37,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 38,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 39,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 40,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 41,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 42,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 43,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 44,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 45,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 46,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 47,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 48,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 49,
                            EventId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 50,
                            EventId = 1,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("EventsTicketingSystem.Models.Ticket", b =>
                {
                    b.HasOne("EventsTicketingSystem.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventsTicketingSystem.Models.Event", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
